# Generated by Django 4.1 on 2022-08-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipesubscriptionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeSubscriptionManager',
        ),
    ]
