# Generated by Django 4.1 on 2022-08-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shopping_cart_shopping_cart_unique_owner_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
