# Generated by Django 4.1 on 2022-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_unique_author_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
