# Generated by Django 4.1 on 2022-08-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersubscriptionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscriptionManager',
        ),
    ]
